### ISSUE TITLE
Support runtime variables

### ISSUE THREAD

**Issue by IGassmann** [nuxt-community/proxy-module#72]
### What problem does this feature solve?

[Runtime variables](https://nuxtjs.org/guide/runtime-config) are now supported by Nuxt. Thus, the proxy-module needs to be updated to support it for its "target" value.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/proxy-module/issues/c45">#c45</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @IGassmann. I think you either misunderstood the usage of runtime config or this module. It is for SSR runtime but proxy module uses a server middleware injected to nuxt server stack so you can always change it without need to rebuild :)

**Comment by IGassmann** [comment]
Hey! Just to confirm. So configuring the module with the following will use the value of API_URL at runtime?

```js
proxy: {
  '/api/': {
    target: process.env.API_URL,
    pathRewrite: {
      '^/api/': '',
    },
  },
},
```

**Comment by pi0** [comment]
@IGassmann Yes it should work. At runtime, you have to make requests without baseURL when making http requests. Using [`axios.proxy`](https://axios.nuxtjs.org/options.html#proxy] to `true` will also automatically set baseURL.

Another alternative approach we can use [axios runtimeConfig](https://axios.nuxtjs.org/options.html#runtime-config)

Summary: Proxy and RuntimeConfig (new) are two different approaches to set base URL at runtime without need to rebuild. Benefit if proxy approach is that it also resolves CORS issues. Benefit of runtimeConfig is it can make direct requests which is faster and we may also use it for static target (re-generate is needed still)

**Comment by IGassmann** [comment]
@pi0 the confusing part is that Nuxt building throws the following error if the environment variable isn't present at build time. Can this error be silenced since the variable will anyway be read at runtime?

```
ERROR  [HPM] Missing "target" option. Example: {target: "http://www.example.org"}

  at Object.createConfig (/usr/src/app/node_modules/http-proxy-middleware/lib/config-factory.js:43:11)
  at new HttpProxyMiddleware (/usr/src/app/node_modules/http-proxy-middleware/lib/index.js:17:30)
  at module.exports (/usr/src/app/node_modules/http-proxy-middleware/index.js:4:10)
  at /usr/src/app/node_modules/@nuxtjs/proxy/lib/module.js:63:30
  at Array.forEach (<anonymous>)
  at ModuleContainer.proxyModule (/usr/src/app/node_modules/@nuxtjs/proxy/lib/module.js:61:9)
  at ModuleContainer.addModule (/usr/src/app/node_modules/@nuxt/core/dist/core.js:229:34)
  at ModuleContainer.requireModule (/usr/src/app/node_modules/@nuxt/core/dist/core.js:142:17)
  at ModuleContainer.axiosModule (/usr/src/app/node_modules/@nuxtjs/axios/lib/module.js:115:10)
  at ModuleContainer.addModule (/usr/src/app/node_modules/@nuxt/core/dist/core.js:229:34)
```

**Comment by pi0** [comment]
I made a new issue for that @IGassmann (#74)
